import { applyStaticI18n } from './core/i18n';
import { initShell } from './app/shell';
import { initSession } from './features/session';
import { initOnboarding } from './features/setup';
import { initDescargar } from './features/download';
import { initSearch } from './features/search';
import { initQueueView } from './features/queue';
import { initAccount } from './features/youtube-account';
import { initLibrary } from './features/library';
import { initSettings } from './features/settings';

applyStaticI18n();
initShell();
void initSession();
initQueueView();
initDescargar();
initSearch();
initAccount();
initLibrary();
void initSettings();
void initOnboarding();
